package charlesli.com.personalvocabbuilder.sqlDatabase;

/**
 * Created by charles on 2016-04-22.
 */
public class DefaultVocab {
    public static final String [] vocabGMAT = {
            "Abaft",
            "Abandon",
            "Abase",
            "Abbreviate",
            "Abdicate",
            "Abhor",
            "Abject",
            "Abjure",
            "Abnegation",
            "Abominate",
            "Abridge",
            "Abrogate",
            "Abrupt",
            "Abscond",
            "Absolve",
            "Abstemious",
            "Abstruse",
            "Abysmal",
            "Accede",
            "Acclaim",
            "Accrue",
            "Acquiesce",
            "Acrid",
            "Adamant",
            "Addled",
            "Adept",
            "Adjure",
            "Adroit",
            "Adulation",
            "Adulterate",
            "Adversary",
            "Affable",
            "Affinity",
            "Aggrandize",
            "Agrarian",
            "Alacrity",
            "Alchemist",
            "Alchemy",
            "Allegory",
            "Alleviate",
            "Allocate",
            "Allude",
            "Aloof",
            "Altercation",
            "Altruistic",
            "Amalgamate",
            "Amass",
            "Ambiguous",
            "Ambivalent",
            "Ameliorate",
            "Amendment",
            "Amiable",
            "Amity",
            "Analogy",
            "Anchorage",
            "Anecdote",
            "Animosity",
            "Anoint",
            "Anonymous",
            "Antagonism",
            "Antipathy",
            "Apathy",
            "Appease",
            "Apposite",
            "Apprehensive",
            "Arable",
            "Arcane",
            "Archetype",
            "Ardent",
            "Arduous",
            "Arrogant",
            "Arrogate",
            "Artifice",
            "Aseptic",
            "Askance",
            "Asperity",
            "Aspirant",
            "Assess",
            "Assiduous",
            "Assuage",
            "Astute",
            "Attenuate",
            "Atypical",
            "Audacious",
            "Augment",
            "August",
            "Auspicious",
            "Authentic",
            "Authoritarian",
            "Autocrat",
            "Aver",
            "Azure",
            "Baleful",
            "Banal",
            "Baneful",
            "Baroque",
            "Bastion",
            "Batten",
            "Bauble",
            "Beget",
            "Beholden",
            "Behoove",
            "Belittle",
            "Bellicose",
            "Bemuse",
            "Benefactor",
            "Benevolent",
            "Benign",
            "Berate",
            "Beseech",
            "Besmirch",
            "Bestial",
            "Betroth",
            "Biased",
            "Blatant",
            "Blighted",
            "Bode",
            "Bombast",
            "Bombastic",
            "Boor",
            "Breadth",
            "Brevity",
            "Brindled",
            "Broach",
            "Brusque",
            "Bumptious",
            "Bungler",
            "Burgeon",
            "Burly",
            "Burnish"
    };
    public static final String [] definitionGMAT = {
            "adj: on or toward the rear of a ship",
            "v: to leave behind",
            "v: to degrade",
            "v: to shorten; compress",
            "v: to reject, renounce",
            "v: to hate",
            "adj: of the worst or lowest degree",
            "v: to give up",
            "n: a denial",
            "v: to loathe; to hate",
            "v: to shorten; to limit",
            "v: to cancel by authority",
            "adj: happening or ending unexpectedly",
            "v: to go away hastily or secretly; to hide",
            "v: to forgive; to acquit",
            "adj: sparing in use of food or drinks",
            "adj: hard to understand; deep",
            "adj: very deep",
            "v: to comply with",
            "n: loud approval; applause",
            "v: a natural growth; a periodic increase",
            "v: to agree without protest",
            "adj: sharp; bitter; foul smelling",
            "adj: not yielding, firm",
            "adj: rotten",
            "adj: skilled; practiced",
            "v: solemnly ordered",
            "adj: expert or skillful",
            "n: praise in excess",
            "v: to corrupt, debase, or make impure",
            "n: an enemy; foe",
            "adj: friendly; amiable; good-natured",
            "n: a connection; similarity of structure",
            "v: to make more powerful",
            "adj: of the land",
            "n: eager readiness or speed",
            "n: a person who studies chemistry",
            "n: any mysterious change of substance or nature",
            "n: a symbolic description",
            "v: to lessen or make easier",
            "v: to set aside; designate; assign",
            "v: to refer indirectly to something",
            "adj: distant in interest; reserved",
            "n: controversy; dispute",
            "adj: unselfish",
            "v: to mix, merge, combine",
            "v: to collect together; accumulate",
            "adj: not clear; uncertain; vague",
            "adj: undecided",
            "v: to improve or make better",
            "n: a positive change",
            "adj: friendly",
            "n: friendly relations",
            "n: similarity; correlation; parallelism",
            "n: something that can be relied on",
            "n: a short account of happenings",
            "n: a feeling of hatred or ill will",
            "v: to crown; ordain",
            "adj: nameless; unidentified",
            "n: hostility; opposition",
            "n: a strong dislike or repugnance",
            "n: lack of emotion or interest",
            "v: to satisfy; to calm",
            "adj: suitable; apt; relevant",
            "adj: fearful; aware; conscious",
            "adj: suitable as land for plowing",
            "adj: obscure; secret; mysterious",
            "n: original pattern or model; prototype",
            "adj: with passionate or intense feelings",
            "adj: laborious, difficult; strenuous",
            "adj: acting superior to others; conceited",
            "v: to claim or demand unduly",
            "n: skill in a craft",
            "adj: germ free",
            "adv: a sideways glance of disapproval",
            "n: harshness",
            "n: a person who goes after high goals",
            "v: to estimate the value of",
            "adj: carefully attentive; industrious",
            "v: to relieve; ease; make less severe",
            "adj: cunning; sly; crafty",
            "v: to thin out; to weaken",
            "adj: something that is abnormal",
            "adj: fearless; bold",
            "v: to increase or add to; to make larger",
            "adj: to be imposing or magnificent",
            "adj: being of a good omen; successful",
            "adj: real; genuine; trustworthy",
            "n: acting as a dictator",
            "n: an absolute ruler",
            "v: to affirm as true",
            "adj: the clear blue color of the sky",
            "adj: harmful, malign, detrimental",
            "adj: trite; without freshness or originality",
            "adj: deadly or causing distress, death",
            "adj: extravagant; ornate; embellished",
            "n: a fortified place or strong defense",
            "v: to gain",
            "n: a showy yet useless thing",
            "v: to bring into being",
            "adj: indebted to",
            "v: to be advantageous; to be necessary",
            "v: to make small; to think lightly of",
            "adj: quarrelsome; warlike",
            "v: to preoccupy in thought",
            "n: one who helps others; a donor",
            "adj: kind; generous",
            "adj: mild; harmless",
            "v: scold; reprove; reproach; criticize",
            "v: to ask earnestly",
            "v: to dirty or discolor",
            "adj: having the qualities of a beast; brutal",
            "v: to promise or pledge in marriage",
            "adj: prejudiced; influenced; not neutral",
            "adj: obvious; unmistakable; crude; vulgar",
            "adj: causing frustration or destruction",
            "v: to foretell something",
            "n: pompous speech; pretentious words",
            "adj: pompous; wordy; turgid",
            "n: a rude person",
            "n: the distance from one side to another",
            "n: briefness; shortness",
            "adj: mixed with a darker color",
            "v: to introduce into conversation",
            "adj: abrupt in manner or speech",
            "adj: arrogant",
            "n: a clumsy person",
            "v: to grow or develop quickly",
            "adj: strong; bulky; stocky",
            "v: to polish by rubbing"
    };
}
