package charlesli.com.personalvocabbuilder.sqlDatabase;

/**
 * Created by charles on 2016-04-22.
 */
public class DefaultVocab {
    public static final String [] vocabGMAT = {
            "Abaft",
            "Abandon",
            "Abase",
            "Abbreviate",
            "Abdicate",
            "Abhor",
            "Abject",
            "Abjure",
            "Abnegation",
            "Abominate",
            "Abridge",
            "Abrogate",
            "Abrupt",
            "Abscond",
            "Absolve",
            "Abstemious",
            "Abstruse",
            "Abysmal",
            "Accede",
            "Acclaim",
            "Accrue",
            "Acquiesce",
            "Acrid",
            "Adamant",
            "Addled",
            "Adept",
            "Adjure",
            "Adroit",
            "Adulation",
            "Adulterate",
            "Adversary",
            "Affable",
            "Affinity",
            "Aggrandize",
            "Agrarian",
            "Alacrity",
            "Alchemist",
            "Alchemy",
            "Allegory",
            "Alleviate",
            "Allocate",
            "Allude",
            "Aloof",
            "Altercation",
            "Altruistic",
            "Amalgamate",
            "Amass",
            "Ambiguous",
            "Ambivalent",
            "Ameliorate",
            "Amendment",
            "Amiable",
            "Amity",
            "Analogy",
            "Anchorage",
            "Anecdote",
            "Animosity",
            "Anoint",
            "Anonymous",
            "Antagonism",
            "Antipathy",
            "Apathy",
            "Appease",
            "Apposite",
            "Apprehensive",
            "Arable",
            "Arcane",
            "Archetype",
            "Ardent",
            "Arduous",
            "Arrogant",
            "Arrogate",
            "Artifice",
            "Aseptic",
            "Askance",
            "Asperity",
            "Aspirant",
            "Assess",
            "Assiduous",
            "Assuage",
            "Astute",
            "Attenuate",
            "Atypical",
            "Audacious",
            "Augment",
            "August",
            "Auspicious",
            "Authentic",
            "Authoritarian",
            "Autocrat",
            "Aver",
            "Azure",
            "Baleful",
            "Banal",
            "Baneful",
            "Baroque",
            "Bastion",
            "Batten",
            "Bauble",
            "Beget",
            "Beholden",
            "Behoove",
            "Belittle",
            "Bellicose",
            "Bemuse",
            "Benefactor",
            "Benevolent",
            "Benign",
            "Berate",
            "Beseech",
            "Besmirch",
            "Bestial",
            "Betroth",
            "Biased",
            "Blatant",
            "Blighted",
            "Bode",
            "Bombast",
            "Bombastic",
            "Boor",
            "Breadth",
            "Brevity",
            "Brindled",
            "Broach",
            "Brusque",
            "Bumptious",
            "Bungler",
            "Burgeon",
            "Burly",
            "Burnish",
            "Cabal",
            "Cacophonous",
            "Cajole",
            "Calamity",
            "Caliber",
            "Callow",
            "Calumny",
            "Canard",
            "Candid",
            "Cant",
            "Capricious",
            "Captious",
            "Cascade",
            "Castigate",
            "Cataclysm",
            "Caustic",
            "Cavil",
            "Censor",
            "Ceremonious",
            "Cessation",
            "Chaffing",
            "Charisma",
            "Chary",
            "Chaste",
            "Chastise",
            "Cherish",
            "Chicanery",
            "Chimera",
            "Chortle",
            "Circumspect",
            "Citadel",
            "Clandestine",
            "Clemency",
            "Coalesce",
            "Coda",
            "Coddle",
            "Codify",
            "Cogitate",
            "Cognizant",
            "Cohesion",
            "Cohort",
            "Collaborate",
            "Collusion",
            "Commiserate",
            "Commodious",
            "Communal",
            "Compatible",
            "Complacent",
            "Compliant",
            "Comport",
            "Comprehensive",
            "Compromise",
            "Conceit",
            "Conciliation",
            "Conciliatory",
            "Concise",
            "Condone",
            "Confluence",
            "Conglomeration",
            "Conjoin",
            "Conjure",
            "Connivance",
            "Consecrate",
            "Consequential",
            "Consort",
            "Conspicuous",
            "Constrain",
            "Consummation",
            "Contempt",
            "Contentious",
            "Contest",
            "Contumacious",
            "Conundrum",
            "Conventional",
            "Conviviality",
            "Convoke",
            "Copious",
            "Corpulence",
            "Correlate",
            "Corroborate",
            "Covenant",
            "Covetous",
            "Cower",
            "Craven",
            "Culpable",
            "Curb",
            "Curmudgeon",
            "Cursory",
            "Cynic",
            "Dais",
            "Dally",
            "Dank",
            "Dauntless",
            "Dearth",
            "Debacle",
            "Debase",
            "Debilitate",
            "Decadence",
            "Deciduous",
            "Decisiveness",
            "Decry",
            "Deferential",
            "Defunct",
            "Deign",
            "Deleterious",
            "Delineate",
            "Deliquesce",
            "Delusion",
            "Demise",
            "Demur",
            "Denounce",
            "Depict",
            "Deplete",
            "Depravity",
            "Depredation",
            "Deride",
            "Derision",
            "Derisive",
            "Derogatory",
            "Descant",
            "Desecrate",
            "Desist",
            "Desolate",
            "Despoil",
            "Despotism",
            "Destitute",
            "Deter",
            "Determinate",
            "Devoid",
            "Dexterous",
            "Diatribe",
            "Dichotomy",
            "Didactic",
            "Diffidence",
            "Diffident",
            "Dilettante",
            "Diligence",
            "Din",
            "Dint",
            "Disapprobation",
            "Disarray",
            "Disavow",
            "Discerning",
            "Discomfit",
            "Discord",
            "Discriminate",
            "Disentangle",
            "Disheartened",
            "Disparage",
            "Disparate",
            "Disparity",
            "Dispassionate",
            "Disperse",
            "Disputatious",
            "Disseminate",
            "Dissent",
            "Dissonant",
            "Distant",
            "Distention",
            "Diverge",
            "Diverse",
            "Divestiture",
            "Docile",
            "Dogma",
            "Dogmatic",
            "Dormant",
            "Doting",
            "Doughty",
            "Dowdy",
            "Duplicity",
            "Duress",
            "Earthy",
            "Ebullience",
            "Eccentric",
            "Effusive",
            "Egress",
            "Elaboration",
            "Eloquence",
            "Elucidate",
            "Elusive",
            "Epitaph",
            "Epitome",
            "Equivocal",
            "Equivocations",
            "Errant",
            "Erratic",
            "Evoke",
            "Exculpate",
            "Execute",
            "Exemplary",
            "Exhaustive",
            "Exhume",
            "Exposition",
            "Expunge",
            "Extant",
            "Extol",
            "Extraneous",
            "Extricable",
            "Exultation",
            "Fastidious",
            "Fatuous",
            "Fealty",
            "Feasible",
            "Fecund",
            "Feign",
            "Foray",
            "Forbearance",
            "Forensic",
            "Fortitude",
            "Fortuitous",
            "Foster",
            "Frugality",
            "Fulminate",
            "Fulsome",
            "Fundamental",
            "Furtive",
            "Fustian",
            "Garrulous",
            "Gauche",
            "Gauntlet",
            "Generic",
            "Genial",
            "Genre",
            "Gnarled",
            "Gourmand",
            "Grandiose",
            "Gravity",
            "Gregarious",
            "Guffaw",
            "Guile",
            "Halcyon",
            "Hamper",
            "Haphazard",
            "Hapless",
            "Harangue",
            "Hedonistic",
            "Heresy",
            "Hiatus",
            "Hoary",
            "Homage",
            "Homeostasis",
            "Homily",
            "Hubris",
            "Humility",
            "Hybrid",
            "Hypocritical",
            "Hypothetical"
    };
    public static final String [] definitionGMAT = {
            "adj: on or toward the rear of a ship",
            "v: to leave behind",
            "v: to degrade",
            "v: to shorten; compress",
            "v: to reject, renounce",
            "v: to hate",
            "adj: of the worst or lowest degree",
            "v: to give up",
            "n: a denial",
            "v: to loathe; to hate",
            "v: to shorten; to limit",
            "v: to cancel by authority",
            "adj: happening or ending unexpectedly",
            "v: to go away hastily or secretly; to hide",
            "v: to forgive; to acquit",
            "adj: sparing in use of food or drinks",
            "adj: hard to understand; deep",
            "adj: very deep",
            "v: to comply with",
            "n: loud approval; applause",
            "v: a natural growth; a periodic increase",
            "v: to agree without protest",
            "adj: sharp; bitter; foul smelling",
            "adj: not yielding, firm",
            "adj: rotten",
            "adj: skilled; practiced",
            "v: solemnly ordered",
            "adj: expert or skillful",
            "n: praise in excess",
            "v: to corrupt, debase, or make impure",
            "n: an enemy; foe",
            "adj: friendly; amiable; good-natured",
            "n: a connection; similarity of structure",
            "v: to make more powerful",
            "adj: of the land",
            "n: eager readiness or speed",
            "n: a person who studies chemistry",
            "n: any mysterious change of substance or nature",
            "n: a symbolic description",
            "v: to lessen or make easier",
            "v: to set aside; designate; assign",
            "v: to refer indirectly to something",
            "adj: distant in interest; reserved",
            "n: controversy; dispute",
            "adj: unselfish",
            "v: to mix, merge, combine",
            "v: to collect together; accumulate",
            "adj: not clear; uncertain; vague",
            "adj: undecided",
            "v: to improve or make better",
            "n: a positive change",
            "adj: friendly",
            "n: friendly relations",
            "n: similarity; correlation; parallelism",
            "n: something that can be relied on",
            "n: a short account of happenings",
            "n: a feeling of hatred or ill will",
            "v: to crown; ordain",
            "adj: nameless; unidentified",
            "n: hostility; opposition",
            "n: a strong dislike or repugnance",
            "n: lack of emotion or interest",
            "v: to satisfy; to calm",
            "adj: suitable; apt; relevant",
            "adj: fearful; aware; conscious",
            "adj: suitable as land for plowing",
            "adj: obscure; secret; mysterious",
            "n: original pattern or model; prototype",
            "adj: with passionate or intense feelings",
            "adj: laborious, difficult; strenuous",
            "adj: acting superior to others; conceited",
            "v: to claim or demand unduly",
            "n: skill in a craft",
            "adj: germ free",
            "adv: a sideways glance of disapproval",
            "n: harshness",
            "n: a person who goes after high goals",
            "v: to estimate the value of",
            "adj: carefully attentive; industrious",
            "v: to relieve; ease; make less severe",
            "adj: cunning; sly; crafty",
            "v: to thin out; to weaken",
            "adj: something that is abnormal",
            "adj: fearless; bold",
            "v: to increase or add to; to make larger",
            "adj: to be imposing or magnificent",
            "adj: being of a good omen; successful",
            "adj: real; genuine; trustworthy",
            "n: acting as a dictator",
            "n: an absolute ruler",
            "v: to affirm as true",
            "adj: the clear blue color of the sky",
            "adj: harmful, malign, detrimental",
            "adj: trite; without freshness or originality",
            "adj: deadly or causing distress, death",
            "adj: extravagant; ornate; embellished",
            "n: a fortified place or strong defense",
            "v: to gain",
            "n: a showy yet useless thing",
            "v: to bring into being",
            "adj: indebted to",
            "v: to be advantageous; to be necessary",
            "v: to make small; to think lightly of",
            "adj: quarrelsome; warlike",
            "v: to preoccupy in thought",
            "n: one who helps others; a donor",
            "adj: kind; generous",
            "adj: mild; harmless",
            "v: scold; reprove; reproach; criticize",
            "v: to ask earnestly",
            "v: to dirty or discolor",
            "adj: having the qualities of a beast; brutal",
            "v: to promise or pledge in marriage",
            "adj: prejudiced; influenced; not neutral",
            "adj: obvious; unmistakable; crude; vulgar",
            "adj: causing frustration or destruction",
            "v: to foretell something",
            "n: pompous speech; pretentious words",
            "adj: pompous; wordy; turgid",
            "n: a rude person",
            "n: the distance from one side to another",
            "n: briefness; shortness",
            "adj: mixed with a darker color",
            "v: to introduce into conversation",
            "adj: abrupt in manner or speech",
            "adj: arrogant",
            "n: a clumsy person",
            "v: to grow or develop quickly",
            "adj: strong; bulky; stocky",
            "v: to polish by rubbing",
            "n: a group of persons joined by a secret",
            "adj: sounding jarring",
            "v: to coax with insincere talk",
            "n: disaster",
            "n: quality",
            "adj: being young or immature",
            "n: slander",
            "n: a false statement or rumor",
            "adj: honest; truthful; sincere",
            "n: insincere or hypocritical statements of high ideals",
            "adj: changeable; fickle",
            "adj: disposed to find fault",
            "n/v: waterfall; pour; rush; fall",
            "v: to punish through public criticism",
            "n: an extreme natural force",
            "adj: eating away at; sarcastic words",
            "v: to bicker",
            "v: to examine and delete objectionable material",
            "adj: very formal or proper",
            "n: ceasing; a stopping",
            "n: banter; teasing",
            "n: appeal; magnetism; presence",
            "adj: cautious; being sparing in giving",
            "adj: virtuous; free of obscenity",
            "v: to punish; discipline; admonish",
            "v: to feel love for",
            "n: trickery or deception",
            "n: an impossible fancy",
            "v: to make a gleeful, chuckling sound",
            "adj: considering all circumstances",
            "n: a fortress set up high to defend a city",
            "adj: secret",
            "n: mercy toward an offender; mildness",
            "v: to grow together",
            "n: in music, a concluding passage",
            "v: to treat with tenderness",
            "v: to organize laws or rules into a systematic collection",
            "v: to think hard; ponder; meditate",
            "adj: aware of; perceptive",
            "n: the act of holding together",
            "n: a group; band",
            "v: to work together; cooperate",
            "n: secret agreement for an illegal purpose",
            "v: to show sympathy for",
            "adj: spacious and convenient; roomy",
            "adj: shared or common ownership",
            "adj: in agreement with; harmonious",
            "adj: content; self-satisfied; smug",
            "adj: complying; obeying; yielding",
            "v: fitting in",
            "adj: all-inclusive; complete; thorough",
            "v: to settle by mutual adjustment",
            "n: an exaggerated personal opinion",
            "n: an attempt to make friendly or placate",
            "adj: to reconcile",
            "adj: in few words; brief; condensed",
            "v: to overlook; to forgive",
            "n: a thing which is joined together",
            "n: a collection or mixture of various things",
            "v: to combine",
            "v: to call upon or appeal to; to cause to be, appear",
            "n: a secret cooperation in wrongdoing",
            "v: to declare sacred; to dedicate",
            "adj: following as an effect; important",
            "n/v: a companion, spouse; to associate",
            "adj: easy to see; noticeable",
            "v: to force, compel; to restrain",
            "n: the completion; finish",
            "n: scorn; disrespect",
            "adj: quarrelsome",
            "v: to attempt to disprove or invalidate",
            "adj: resisting authority",
            "n: a puzzle or riddle",
            "adj: traditional; common; routine",
            "n: a fondness for festiveness or joviality",
            "v: a call to assemble",
            "adj: abundant; in great quantities",
            "n: obesity",
            "v: to bring into mutual relation",
            "v: to confirm the validity",
            "n: a binding and solemn agreement",
            "adj: greedy; very desirous",
            "v: to huddle and tremble",
            "n/adj: coward; abject person; cowardly",
            "adj: deserving blame; guilty",
            "n: a restraint or framework",
            "n: an ill-tempered person",
            "adj: hasty; slight",
            "n: one who believes that others are motivated entirely by selfishness",
            "n: a raised platform at one end of a room",
            "v: to loiter; to waste time",
            "adj: damp and chilly",
            "adj: fearless; not discouraged",
            "n: scarcity; shortage",
            "n: disaster; collapse; a rout",
            "v: to make lower in quality",
            "v: to enfeeble; to wear out",
            "n: a decline in morals or art",
            "adj: shedding; temporary",
            "n: an act of being firm or determined",
            "v: to denounce or condemn openly",
            "adj: yielding to the opinion of another",
            "adj: no longer living or existing",
            "v: condescend; stoop",
            "adj: harmful; hurtful; noxious",
            "v: to outline; to describe",
            "v: to dissolve",
            "n: a false belief or opinion",
            "n: ceasing to exist as in death",
            "v/n: to object; objection; misgiving",
            "v: to speak out against; condemn",
            "v: to portray; describe",
            "v: to reduce; to empty, exhaust",
            "n: moral corruption; badness",
            "n: a plundering or laying waste",
            "v: to laugh at with contempt; to mock",
            "n: the act of mocking; ridicule, mockery",
            "adj: showing disrespect or scorn for",
            "adj: belittling; uncomplimentary",
            "v: lengthy talking or writing",
            "v: to profane; violate the sanctity of",
            "v: to stop or cease",
            "adj: to be left alone or made lonely",
            "v: to take everything; plunder",
            "n: tyranny; absolute power or influence",
            "adj: poor; poverty-stricken",
            "v: to prevent; to discourage; hinder",
            "adj: distinct limits",
            "adj: lacking; empty",
            "adj: skillful, quick mentally or physically",
            "n: a bitter or abusive speech",
            "n: a division into two parts or kinds",
            "adj: instructive; dogmatic; preachy",
            "n: a hesitation in asserting oneself",
            "adj: timid; lacking self-confidence",
            "n: an admirer of the fine arts; a dabbler",
            "n: hard word",
            "n: a noise which is loud and continuous",
            "n: strength",
            "n: disapproval",
            "n: disorder",
            "v: to deny; to refuse to acknowledge",
            "adj: distinguishing one thing from another",
            "v: to frustrate the expectations of",
            "n: disagreement; lack of harmony",
            "v: distinguish; demonstrate bias",
            "v: to free from confusion",
            "adj: discouraged; depressed",
            "v: to belittle; undervalue; to discredit",
            "adj: unequal; dissimilar; different",
            "n: difference in form, character, or degree",
            "adj: lack of feeling; impartial",
            "v: to scatter; separate",
            "adj: argumentative; inclined to disputes",
            "v: to circulate; scatter",
            "v: to disagree; differ in opinion",
            "adj: not in harmony; in disagreement",
            "adj: having separations or being reserved",
            "n: inflation or extension",
            "v: separate, split",
            "adj: different; varied",
            "n: being stripped",
            "adj: manageable; obedient; gentle",
            "n: a collection of beliefs",
            "adj: stubborn; biased; opinionated",
            "adj: as if asleep",
            "adj: excessively fond of",
            "adj: brave and strong",
            "adj: shabby in appearance",
            "n: deception",
            "n: imprisonment; the use of threats",
            "adj: unrefined",
            "n: an overflowing of high spirits; effervescence",
            "adj: odd; peculiar; strange",
            "adj: pouring out or forth; overflowing",
            "n: a way out; exit",
            "n: act of clarifying; adding details",
            "n: the ability to speak well",
            "v: to make clear; to explain",
            "adj: hard to catch",
            "n: an inscription on a monument; in honor or memory of a dead person",
            "n: model; typification; representation",
            "adj: doubtful; uncertain",
            "n: a purposely misleading statement",
            "adj: roving in search of adventure",
            "adj: unpredictable; irregular",
            "v: to call forth; provoke",
            "v: to free from guilt",
            "v: to put to death; kill; to carry out; fulfill",
            "adj: serving as an example; outstanding",
            "adj: thorough; complete",
            "v: to unearth; to reveal",
            "n: setting forth facts",
            "v: to blot out; to delete",
            "adj: existing",
            "v: to give great praise",
            "adj: irrelevant; not related",
            "adj: capable of being disentangled",
            "n: the act of rejoicing",
            "adj: difficult to please; dainty",
            "adj: lacking in seriousness; vain and silly",
            "n: loyalty",
            "adj: reasonable; practical",
            "adj: productive",
            "v: pretend",
            "v: to raid for spoils, plunder",
            "n: patience; self-restraint",
            "adj: pertaining to legal or public argument",
            "n: firm courage; strength",
            "adj: happening accidentally",
            "v: to encourage; nurture; support",
            "n: thrift; economical use or expenditure",
            "v: to blame",
            "adj: disgusting due to excess",
            "adj: basic; necessary",
            "adj: secretive; sly",
            "n: pompous talk or writing",
            "adj: extremely talkative or wordy",
            "adj: awkward; lacking social grace",
            "n: a protective glove",
            "adj: common; general",
            "adj: contributing to life; amiable",
            "adj: designating a type of film or book",
            "adj: full of knots; twisted",
            "n: one who eats eagerly",
            "adj: magnificent; flamboyant",
            "n: seriousness",
            "adj: fond of the company of others",
            "n: boisterous laughter",
            "n: slyness; deceit",
            "adj: tranquil; happy",
            "v: interfere with; hinder",
            "adj: disorganized; random",
            "adj: unlucky; unfortunate",
            "n: a lengthy, heartfelt speech",
            "adj: living for pleasure",
            "n: opinion contrary to popular belief",
            "n: interval; break; period of rest",
            "adj: whitened by age",
            "n: honor; respect",
            "n: maintenance of stability",
            "n: solemn moral talk; sermon",
            "n: arrogance",
            "n: lack of pride; modesty",
            "n: anything of mixed origin",
            "adj: two-faced; deceptive",
            "adj: assumed; uncertain; conjectural"


    };
}
